library(rvest)
library(dplyr)
library(stringr)
library(robotstxt)
url <- 'https://companiesmarketcap.com/'
web <- read_html(url)
View(web)
Company_name <- web %>% html_nodes('.company-name') %>% html_text()
View(Company_name)
Company_Values <- web %>% html_nodes('.name-td+ .td-right') %>% html_text()
View(Company_Values)
Current_stock_Values <- web %>% html_nodes('td.rh-sm') %>% html_text()
View(Current_stock_Values)
Current_stock_price <- web %>% html_nodes('.td-right+ .td-right') %>% html_text()
View(Current_stock_price)
Company_List=data.frame(Company_name,Company_Values,Current_stock_Values,Current_stock_price)
View(Company_List)
write.csv(Company_List,"Company_List01.csv")
